project_id = "revision-tracker"

[auth]
site_url = "https://dashboard.prerelease.uk/"
minimum_password_length = 8
password_requirements = "lower_upper_letters_digits_symbols"
additional_redirect_urls = [
  "https://dashboard.prerelease.uk/account/",
  "https://dashboard.prerelease.uk/account/?mode=callback&next=home",
  "https://dashboard.prerelease.uk/account/?mode=callback&next=tracker",
  "https://dashboard.prerelease.uk/account/?mode=recovery&next=home",
  "https://dashboard.prerelease.uk/account/?mode=recovery&next=tracker",
  "http://localhost:5173/account/",
  "http://localhost:5173/account/?mode=callback&next=home",
  "http://localhost:5173/account/?mode=callback&next=tracker",
  "http://localhost:5173/account/?mode=recovery&next=home",
  "http://localhost:5173/account/?mode=recovery&next=tracker",
  "http://127.0.0.1:5173/account/",
  "http://127.0.0.1:5173/account/?mode=callback&next=home",
  "http://127.0.0.1:5173/account/?mode=callback&next=tracker",
  "http://127.0.0.1:5173/account/?mode=recovery&next=home",
  "http://127.0.0.1:5173/account/?mode=recovery&next=tracker",
  "revisiontracker://auth/callback",
]

[auth.email]
enable_confirmations = true
secure_password_change = false
max_frequency = "1m"
otp_expiry = 3600

[functions.delete-account]
verify_jwt = true
