import { DateTime } from 'luxon';
import { displayDay } from './dates';
import { citizenship, currentLocation, rollingAbsences, tripCounts } from './engine';
import { RULES, warningLevel } from './rules';
import type { Counts, Flight, Rolling, State, Timeline, Trip, WindowTotal } from './types';
export const esc = (value: unknown): string => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
export const fmt = (day: string | null) => day ? displayDay(day) : 'Present';
export const range = (start: string, end: string) => `${fmt(start)} → ${fmt(end)}`;
export function field(name: string, label: string, value = '', type = 'text', required = false, help = ''): string {
  return `<label class="bno-field" for="f-${esc(name)}">${esc(label)}<input class="form-control" id="f-${esc(name)}" name="${esc(name)}" type="${type}" value="${esc(value)}" ${required ? 'required' : ''} ${help ? `aria-describedby="h-${esc(name)}"` : ''}>${help ? `<small id="h-${esc(name)}" class="bno-caption">${esc(help)}</small>` : ''}</label>`;
}
export function selectField(name: string, label: string, options: Array<[string, string]>, value: string): string {
  return `<label class="bno-field" for="f-${name}">${esc(label)}<select class="form-control" id="f-${name}" name="${name}">${options.map(([v, l]) => `<option value="${esc(v)}" ${v === value ? 'selected' : ''}>${esc(l)}</option>`).join('')}</select></label>`;
}
export const notesField = (value = '') => `<label class="bno-field bno-wide" for="f-notes">Notes<textarea class="form-control" id="f-notes" name="notes" maxlength="10000">${esc(value)}</textarea></label>`;
export const button = (label: string, attrs: string, primary = false) => `<button type="button" class="button button--${primary ? 'primary' : 'quiet'} button--compact" ${attrs}>${esc(label)}</button>`;
export function metric(title: string, counts: Counts | undefined, limit: number, window: string, complete: boolean, thresholds: number[], extra = ''): string {
  if (!counts) return `<article class="surface-card bno-card"><p class="section-kicker">${esc(title)}</p><h2>Not configured</h2><p class="bno-caption">Set your dates to see this calculation.</p>${button('Configure', 'data-go="settings"')}</article>`;
  const level = complete ? warningLevel(counts.official, limit, thresholds) : 'Needs review';
  return `<article class="surface-card bno-card"><p class="section-kicker">${esc(title)}</p><span class="bno-number">${counts.official} <small>/ ${limit} days</small></span><p class="bno-caption">Official whole-day count</p><progress max="${limit}" value="${Math.min(counts.official, limit)}" aria-label="${esc(title)} official usage"></progress><p>${Math.max(0, limit - counts.official)} remaining · ${(counts.official / limit * 100).toFixed(1)}% used${counts.official > limit ? ` · ${counts.official - limit} over` : ''}</p><p class="bno-caption">Conservative: <strong>${counts.conservative} / ${limit}</strong></p><p class="bno-caption">${esc(window)}</p><span class="bno-badge" data-level="${level}">${level}</span>${extra}</article>`;
}
export function overview(state: State, timeline: Timeline): string {
  const r = rollingAbsences(timeline), c = citizenship(timeline), location = currentLocation(timeline, new Date().toISOString());
  const thresholds = state.settings.warning_thresholds;
  const lastReturn = timeline.trips.filter(t => t.returned).map(t => t.returned!).sort().at(-1);
  return `${timeline.trips.length === 0 ? `<section class="surface-card bno-panel bno-empty"><h2>BNO Tracker</h2><p>No travel recorded yet.</p><p class="bno-caption">Add your journeys and configure your dates. Empty history does not establish UK presence.</p>${button('Add Flight', 'data-add="flight"', true)} ${button('Add Manual Trip', 'data-add="manual"')}</section>` : ''}<div class="bno-grid"><article class="surface-card bno-card"><p class="section-kicker">Current recorded status</p><h2>${esc(location.state)}</h2>${location.country ? `<p>${esc(location.country)}</p>` : ''}${location.trip ? `<p class="bno-caption">Away since ${fmt(location.trip.departure)}<br>${tripCounts(location.trip, timeline.today).official} completed official days · ${tripCounts(location.trip, timeline.today).conservative} conservative</p><p class="bno-caption">Today is provisional.</p>` : lastReturn ? `<p class="bno-caption">Last returned ${fmt(lastReturn)}</p>` : ''}<p class="bno-caption">Based on recorded travel and your coverage declaration.</p></article>
  ${metric(state.settings.ilr_date ? 'BNO — final rolling window at ILR' : 'BNO — current rolling 12 months', r?.current, RULES.bno, r ? range(r.current.start, r.current.end) : '', r?.complete ?? false, thresholds)}
  ${metric('BNO — worst rolling 12 months', r?.worst, RULES.bno, r ? range(r.worst.start, r.worst.end) : '', r?.complete ?? false, thresholds, r ? `<p class="bno-caption">Conservative maximum: ${r.conservativeWorst.conservative}, ${range(r.conservativeWorst.start, r.conservativeWorst.end)}</p>` : '')}
  ${metric('Citizenship — five years', c?.five, RULES.citizenship, c ? range(c.start, c.end) : '', c?.complete ?? false, thresholds, c?.projected ? '<p class="bno-caption">Projection: recorded travel only; future travel remains unknown.</p>' : '')}
  ${metric('Citizenship — final 12 months', c?.year, RULES.finalYear, c ? range(c.yearStart, c.end) : '', c?.complete ?? false, thresholds)}
  <article class="surface-card bno-card"><p class="section-kicker">History coverage</p><h2>${state.settings.coverage_start ? fmt(state.settings.coverage_start) : 'Not configured'}</h2><p class="bno-caption">Initial location: ${esc(state.settings.initial_location)}. Earlier gaps remain unknown.</p>${button('Review settings', 'data-go="settings"')}</article></div>
  ${c ? `<section class="surface-card bno-panel"><h2>Citizenship presence check</h2><p>Caseworker start, ${fmt(c.start)}: <strong>${c.presence}</strong></p><p>Exactly five years earlier, ${fmt(c.anniversaryDay)}: <strong>${c.anniversaryPresence}</strong></p><p class="bno-caption">The public page and caseworker guidance differ by one day. Anniversary-start totals: ${c.alternativeFive.official} official / ${c.alternativeFive.conservative} conservative over five years; ${c.alternativeYear.official} / ${c.alternativeYear.conservative} in the final year.</p>${c.leapBoundary ? '<p class="bno-error">Leap-day boundary: verify the applicable dates before relying on these results.</p>' : ''}<p class="bno-caption">These checks do not establish citizenship eligibility. See Rules &amp; information below.</p></section>` : ''}${notices(timeline)}`;
}
export function notices(t: Timeline): string {
  if (!t.issues.length) return '';
  return `<section class="surface-card bno-panel"><h2>Travel records to review</h2><ul class="bno-notices">${t.issues.map(i => `<li>${esc(i.message)} ${i.recordIds.map(id => button('Review record', `data-review="${esc(id)}"`)).join(' ')}</li>`).join('')}</ul></section>`;
}
export function flightDetails(f: Flight): string {
  const time = (at: string, zone: string) => DateTime.fromISO(at).setZone(zone).toFormat('dd LLL yyyy, HH:mm ZZZZ');
  return `<article class="bno-details-flight"><strong>${esc(f.departure_airport.code)} → ${esc(f.arrival_airport.code)}</strong><p>${esc(time(f.departure_at, f.departure_airport.timezone))} → ${esc(time(f.arrival_at, f.arrival_airport.timezone))}</p><p>${esc(f.departure_airport.country)} → ${esc(f.arrival_airport.country)}</p><p>${esc([f.airline, f.flight_number, f.booking_reference].filter(Boolean).join(' · '))}</p><p>${esc(f.notes)}</p><div class="bno-inline-actions">${button('Edit flight', `data-edit-flight="${esc(f.id)}"`)}${button('Delete flight', `data-delete-flight="${esc(f.id)}"`)}</div></article>`;
}
export function tripDetails(t: Trip, today: string): string {
  const counts = tripCounts(t, today);
  return `<p><strong>${esc(t.countries.join(', ') || 'Destination not recorded')}</strong></p><p>${range(t.departure, t.returned ?? today)}${!t.returned ? ' · Open trip' : ''}</p><p>Official: ${counts.official} · Conservative: ${counts.conservative}</p><p class="bno-caption">${t.source === 'flight' ? `Derived from ${t.flights.length} flights` : t.source === 'manual' ? 'Manual entry' : 'Planned trip'}</p><p>${esc(t.notes)}</p>${t.departureLocation || t.returnLocation ? `<p class="bno-caption">${esc(t.departureLocation)} → ${esc(t.returnLocation)}</p>` : ''}${t.flights.length ? `<p class="bno-caption">${esc([t.flights[0].departure_airport.code, ...t.flights.map(f => f.arrival_airport.code)].join(' → '))}</p>` : ''}${t.flights.map(flightDetails).join('')}<div class="bno-inline-actions">${t.source === 'manual' ? button('Edit manual trip', `data-edit-manual="${esc(t.id)}"`) : ''}${t.source !== 'planned' ? button('Delete trip', `data-delete-trip="${esc(t.id)}"`) : ''}</div>`;
}
export function rulesHtml(): string {
  return `<p>BNO / ILR normally allows no more than ${RULES.bno} days outside the UK in any rolling twelve months. The five-year citizenship route normally allows ${RULES.citizenship} days, with no more than ${RULES.finalYear} in the final twelve months.</p><p>Official counts exclude departure and arrival dates. Conservative counts include both as a personal planning buffer. An ongoing trip’s current UK day remains provisional until midnight.</p><p>Citizenship primary windows use the caseworker convention: the day after the anniversary through the application date. The exact-anniversary interpretation is also shown because public guidance differs. Month subtraction clamps to the last valid day; leap-day cases need review.</p><p>UK airport classification means Great Britain and Northern Ireland. Crown Dependencies and discretionary exceptions require individual review; this tracker does not automatically grant exemptions. A BNO grant date alone does not prove UK presence or eligibility.</p><ul>${RULES.sources.map(([name, url]) => `<li><a href="${url}" target="_blank" rel="noopener noreferrer">${name}</a></li>`).join('')}</ul><p>Planning aid only. Immigration and nationality rules can change. Verify current requirements on GOV.UK before relying on these calculations.</p><p class="bno-caption">Rule definitions checked ${RULES.version}. Airport sources: OurAirports and OpenFlights. <a href="/bno/NOTICE.md">Dataset attribution and licence</a>.</p>`;
}
export function chartHtml(r: Rolling): string {
  const height = 210, width = 760, ceiling = Math.max(200, ...r.points.map(p => p.conservative)), left = 42, top = 18;
  const x = (i: number) => left + i / Math.max(1, r.points.length - 1) * (width - left - 12);
  const y = (v: number) => top + (height - top - 26) * (1 - v / ceiling);
  const points = (mode: 'official' | 'conservative') => r.points.map((p, i) => `${x(i).toFixed(1)},${y(p[mode]).toFixed(1)}`).join(' ');
  return `<svg class="bno-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="Official and conservative rolling absence totals. Use the date slider below to inspect each day."><line x1="${left}" x2="${width - 12}" y1="${y(180)}" y2="${y(180)}" stroke="var(--color-danger)" stroke-dasharray="4 4"/><text x="3" y="${y(180) + 4}">180</text><text x="15" y="${y(0)}">0</text><polyline class="conservative" points="${points('conservative')}" fill="none" stroke-width="1.5"/><polyline class="official" points="${points('official')}" fill="none" stroke-width="2"/><text x="${left}" y="${height - 3}">${fmt(r.points[0].end)}</text><text x="${width - 12}" y="${height - 3}" text-anchor="end">${fmt(r.current.end)}</text></svg><p class="bno-caption">Solid: official · Dashed: conservative · Horizontal reference: 180 days</p><label class="bno-field">Inspect date<input type="range" data-chart-date min="0" max="${r.points.length - 1}" value="${r.points.length - 1}"></label><p class="bno-chart-readout" data-chart-readout aria-live="polite">${chartReadout(r.current)}</p>`;
}
export function chartReadout(p: WindowTotal): string { return `${range(p.start, p.end)} · Official ${p.official} · Conservative ${p.conservative} · Official remaining ${RULES.bno - p.official}`; }
